version: '3'
services:
  api-gateway:
    image: maslow123/keuanganku-apigateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/    
volumes:
  api: