version: '3'
services:  
  userapi:
    image: maslow123/keuanganku-users:latest
    container_name: userapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 50051:50051
    restart: on-failure    
    networks:
      - keuanganku
  posapi:
    image: maslow123/keuanganku-pos:latest
    container_name: posapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 50052:50052
    restart: on-failure    
    networks:
      - keuanganku
  transactionapi:
    image: maslow123/keuanganku-transactions:latest
    container_name: transactionapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 50053:50053
    restart: on-failure    
    networks:
      - keuanganku
  balanceapi:
    image: maslow123/keuanganku-balance:latest
    container_name: balanceapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 50054:50054
    restart: on-failure    
    networks:
      - keuanganku
  testdb:
    image: postgres:latest
    container_name: testdb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - keuanganku
  migratedb:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://${DB_USERNAME}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]
    links:
      - testdb
    networks:
      - keuanganku
  api-gateway:
    image: maslow123/keuanganku-apigateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/Dockerfile    
    ports:
      - 3000:3000
    restart: on-failure    
    networks:
      - keuanganku
volumes:
  database_postgres:

networks:
  keuanganku:
    driver: bridge