version: '3'
services:  
  api:
    image: maslow123/keuanganku-service:latest
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 50051:50051
    restart: on-failure    
    networks:
      - keuanganku
  testdb:
    image: postgres:latest
    container_name: testdb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - keuanganku
  migratedb:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://${DB_USERNAME}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]
    links:
      - testdb
    networks:
      - keuanganku
  api-gateway:
    image: maslow123/api-gateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/Dockerfile    
    ports:
      - 3000:3000
    restart: on-failure    
    networks:
      - keuanganku
volumes:
  database_postgres:

networks:
  keuanganku:
    driver: bridge