// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: transactions/pb/pos.proto

package pb

import (
	context "context"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTotalPosRequest_ActionTransaction int32

const (
	UpdateTotalPosRequest_INCREASE UpdateTotalPosRequest_ActionTransaction = 0
	UpdateTotalPosRequest_DECREASE UpdateTotalPosRequest_ActionTransaction = 1
)

// Enum value maps for UpdateTotalPosRequest_ActionTransaction.
var (
	UpdateTotalPosRequest_ActionTransaction_name = map[int32]string{
		0: "INCREASE",
		1: "DECREASE",
	}
	UpdateTotalPosRequest_ActionTransaction_value = map[string]int32{
		"INCREASE": 0,
		"DECREASE": 1,
	}
)

func (x UpdateTotalPosRequest_ActionTransaction) Enum() *UpdateTotalPosRequest_ActionTransaction {
	p := new(UpdateTotalPosRequest_ActionTransaction)
	*p = x
	return p
}

func (x UpdateTotalPosRequest_ActionTransaction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateTotalPosRequest_ActionTransaction) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_pb_pos_proto_enumTypes[0].Descriptor()
}

func (UpdateTotalPosRequest_ActionTransaction) Type() protoreflect.EnumType {
	return &file_transactions_pb_pos_proto_enumTypes[0]
}

func (x UpdateTotalPosRequest_ActionTransaction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateTotalPosRequest_ActionTransaction.Descriptor instead.
func (UpdateTotalPosRequest_ActionTransaction) EnumDescriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{11, 0}
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Total     int32  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Color     string `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt int32  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{0}
}

func (x *Pos) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pos) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pos) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Pos) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pos) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Pos) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Pos) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreatePos
type CreatePosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Color  string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *CreatePosRequest) Reset() {
	*x = CreatePosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePosRequest) ProtoMessage() {}

func (x *CreatePosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePosRequest.ProtoReflect.Descriptor instead.
func (*CreatePosRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePosRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePosRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePosRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreatePosRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type CreatePosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePosResponse) Reset() {
	*x = CreatePosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePosResponse) ProtoMessage() {}

func (x *CreatePosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePosResponse.ProtoReflect.Descriptor instead.
func (*CreatePosResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePosResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreatePosResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreatePosResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PosDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PosDetailRequest) Reset() {
	*x = PosDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PosDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDetailRequest) ProtoMessage() {}

func (x *PosDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDetailRequest.ProtoReflect.Descriptor instead.
func (*PosDetailRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{3}
}

func (x *PosDetailRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PosDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Pos    *Pos   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *PosDetailResponse) Reset() {
	*x = PosDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PosDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDetailResponse) ProtoMessage() {}

func (x *PosDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDetailResponse.ProtoReflect.Descriptor instead.
func (*PosDetailResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{4}
}

func (x *PosDetailResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PosDetailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PosDetailResponse) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type GetPosListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page   int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	UserId int32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetPosListRequest) Reset() {
	*x = GetPosListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPosListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPosListRequest) ProtoMessage() {}

func (x *GetPosListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPosListRequest.ProtoReflect.Descriptor instead.
func (*GetPosListRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{5}
}

func (x *GetPosListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPosListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPosListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPosListRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetPosListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Page   int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Pos    []*Pos `protobuf:"bytes,5,rep,name=pos,proto3" json:"pos,omitempty"`
}

func (x *GetPosListResponse) Reset() {
	*x = GetPosListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPosListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPosListResponse) ProtoMessage() {}

func (x *GetPosListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPosListResponse.ProtoReflect.Descriptor instead.
func (*GetPosListResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{6}
}

func (x *GetPosListResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPosListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetPosListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPosListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPosListResponse) GetPos() []*Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type UpdatePosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *UpdatePosRequest) Reset() {
	*x = UpdatePosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePosRequest) ProtoMessage() {}

func (x *UpdatePosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePosRequest.ProtoReflect.Descriptor instead.
func (*UpdatePosRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePosRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePosRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePosRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type UpdatePosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Pos    *Pos   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *UpdatePosResponse) Reset() {
	*x = UpdatePosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePosResponse) ProtoMessage() {}

func (x *UpdatePosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePosResponse.ProtoReflect.Descriptor instead.
func (*UpdatePosResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePosResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatePosResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdatePosResponse) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type DeletePosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePosRequest) Reset() {
	*x = DeletePosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePosRequest) ProtoMessage() {}

func (x *DeletePosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePosRequest.ProtoReflect.Descriptor instead.
func (*DeletePosRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePosRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeletePosResponse) Reset() {
	*x = DeletePosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePosResponse) ProtoMessage() {}

func (x *DeletePosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePosResponse.ProtoReflect.Descriptor instead.
func (*DeletePosResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePosResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeletePosResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTotalPosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32                                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action UpdateTotalPosRequest_ActionTransaction `protobuf:"varint,2,opt,name=action,proto3,enum=pos.UpdateTotalPosRequest_ActionTransaction" json:"action,omitempty"`
	Amount int32                                   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *UpdateTotalPosRequest) Reset() {
	*x = UpdateTotalPosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTotalPosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTotalPosRequest) ProtoMessage() {}

func (x *UpdateTotalPosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTotalPosRequest.ProtoReflect.Descriptor instead.
func (*UpdateTotalPosRequest) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTotalPosRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTotalPosRequest) GetAction() UpdateTotalPosRequest_ActionTransaction {
	if x != nil {
		return x.Action
	}
	return UpdateTotalPosRequest_INCREASE
}

func (x *UpdateTotalPosRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateTotalPosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total  int32  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UpdateTotalPosResponse) Reset() {
	*x = UpdateTotalPosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_pb_pos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTotalPosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTotalPosResponse) ProtoMessage() {}

func (x *UpdateTotalPosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_pb_pos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTotalPosResponse.ProtoReflect.Descriptor instead.
func (*UpdateTotalPosResponse) Descriptor() ([]byte, []int) {
	return file_transactions_pb_pos_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTotalPosResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateTotalPosResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateTotalPosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_transactions_pb_pos_proto protoreflect.FileDescriptor

var file_transactions_pb_pos_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x70, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6f, 0x73,
	0x1a, 0x0a, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01, 0x0a,
	0x03, 0x50, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x06, 0xea, 0xde, 0x1f, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xea, 0xde, 0x1f, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x08, 0xea, 0xde, 0x1f, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1f,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xea,
	0xde, 0x1f, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x2d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x0e, 0xea, 0xde, 0x1f, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x0e, 0xea, 0xde, 0x1f, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x69, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x51, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x50,
	0x6f, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x5d, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x6a,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x42, 0x0a, 0xea, 0xde, 0x1f, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xea, 0xde, 0x1f, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x42, 0x08, 0xea, 0xde, 0x1f, 0x04, 0x70, 0x61, 0x67, 0x65, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x09, 0xea, 0xde, 0x1f, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x23, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x42, 0x07, 0xea, 0xde,
	0x1f, 0x03, 0x70, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x4c, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x5d, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x50,
	0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xb6,
	0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4e, 0x43, 0x52, 0x45, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x43,
	0x52, 0x45, 0x41, 0x53, 0x45, 0x10, 0x01, 0x22, 0x5c, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xa6, 0x03, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x12, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x6f, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x73, 0x2e,
	0x50, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x6f, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17,
	0x5a, 0x15, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transactions_pb_pos_proto_rawDescOnce sync.Once
	file_transactions_pb_pos_proto_rawDescData = file_transactions_pb_pos_proto_rawDesc
)

func file_transactions_pb_pos_proto_rawDescGZIP() []byte {
	file_transactions_pb_pos_proto_rawDescOnce.Do(func() {
		file_transactions_pb_pos_proto_rawDescData = protoimpl.X.CompressGZIP(file_transactions_pb_pos_proto_rawDescData)
	})
	return file_transactions_pb_pos_proto_rawDescData
}

var file_transactions_pb_pos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transactions_pb_pos_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_transactions_pb_pos_proto_goTypes = []interface{}{
	(UpdateTotalPosRequest_ActionTransaction)(0), // 0: pos.UpdateTotalPosRequest.ActionTransaction
	(*Pos)(nil),                    // 1: pos.Pos
	(*CreatePosRequest)(nil),       // 2: pos.CreatePosRequest
	(*CreatePosResponse)(nil),      // 3: pos.CreatePosResponse
	(*PosDetailRequest)(nil),       // 4: pos.PosDetailRequest
	(*PosDetailResponse)(nil),      // 5: pos.PosDetailResponse
	(*GetPosListRequest)(nil),      // 6: pos.GetPosListRequest
	(*GetPosListResponse)(nil),     // 7: pos.GetPosListResponse
	(*UpdatePosRequest)(nil),       // 8: pos.UpdatePosRequest
	(*UpdatePosResponse)(nil),      // 9: pos.UpdatePosResponse
	(*DeletePosRequest)(nil),       // 10: pos.DeletePosRequest
	(*DeletePosResponse)(nil),      // 11: pos.DeletePosResponse
	(*UpdateTotalPosRequest)(nil),  // 12: pos.UpdateTotalPosRequest
	(*UpdateTotalPosResponse)(nil), // 13: pos.UpdateTotalPosResponse
}
var file_transactions_pb_pos_proto_depIdxs = []int32{
	1,  // 0: pos.PosDetailResponse.pos:type_name -> pos.Pos
	1,  // 1: pos.GetPosListResponse.pos:type_name -> pos.Pos
	1,  // 2: pos.UpdatePosResponse.pos:type_name -> pos.Pos
	0,  // 3: pos.UpdateTotalPosRequest.action:type_name -> pos.UpdateTotalPosRequest.ActionTransaction
	2,  // 4: pos.PosService.CreatePos:input_type -> pos.CreatePosRequest
	6,  // 5: pos.PosService.GetPosByUser:input_type -> pos.GetPosListRequest
	4,  // 6: pos.PosService.PosDetail:input_type -> pos.PosDetailRequest
	8,  // 7: pos.PosService.UpdatePosByUser:input_type -> pos.UpdatePosRequest
	10, // 8: pos.PosService.DeletePosByUser:input_type -> pos.DeletePosRequest
	12, // 9: pos.PosService.UpdateTotalPosByUser:input_type -> pos.UpdateTotalPosRequest
	3,  // 10: pos.PosService.CreatePos:output_type -> pos.CreatePosResponse
	7,  // 11: pos.PosService.GetPosByUser:output_type -> pos.GetPosListResponse
	5,  // 12: pos.PosService.PosDetail:output_type -> pos.PosDetailResponse
	9,  // 13: pos.PosService.UpdatePosByUser:output_type -> pos.UpdatePosResponse
	11, // 14: pos.PosService.DeletePosByUser:output_type -> pos.DeletePosResponse
	13, // 15: pos.PosService.UpdateTotalPosByUser:output_type -> pos.UpdateTotalPosResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_transactions_pb_pos_proto_init() }
func file_transactions_pb_pos_proto_init() {
	if File_transactions_pb_pos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transactions_pb_pos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PosDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PosDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPosListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPosListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTotalPosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_pb_pos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTotalPosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transactions_pb_pos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_pb_pos_proto_goTypes,
		DependencyIndexes: file_transactions_pb_pos_proto_depIdxs,
		EnumInfos:         file_transactions_pb_pos_proto_enumTypes,
		MessageInfos:      file_transactions_pb_pos_proto_msgTypes,
	}.Build()
	File_transactions_pb_pos_proto = out.File
	file_transactions_pb_pos_proto_rawDesc = nil
	file_transactions_pb_pos_proto_goTypes = nil
	file_transactions_pb_pos_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PosServiceClient is the client API for PosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PosServiceClient interface {
	CreatePos(ctx context.Context, in *CreatePosRequest, opts ...grpc.CallOption) (*CreatePosResponse, error)
	GetPosByUser(ctx context.Context, in *GetPosListRequest, opts ...grpc.CallOption) (*GetPosListResponse, error)
	PosDetail(ctx context.Context, in *PosDetailRequest, opts ...grpc.CallOption) (*PosDetailResponse, error)
	UpdatePosByUser(ctx context.Context, in *UpdatePosRequest, opts ...grpc.CallOption) (*UpdatePosResponse, error)
	DeletePosByUser(ctx context.Context, in *DeletePosRequest, opts ...grpc.CallOption) (*DeletePosResponse, error)
	UpdateTotalPosByUser(ctx context.Context, in *UpdateTotalPosRequest, opts ...grpc.CallOption) (*UpdateTotalPosResponse, error)
}

type posServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPosServiceClient(cc grpc.ClientConnInterface) PosServiceClient {
	return &posServiceClient{cc}
}

func (c *posServiceClient) CreatePos(ctx context.Context, in *CreatePosRequest, opts ...grpc.CallOption) (*CreatePosResponse, error) {
	out := new(CreatePosResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/CreatePos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posServiceClient) GetPosByUser(ctx context.Context, in *GetPosListRequest, opts ...grpc.CallOption) (*GetPosListResponse, error) {
	out := new(GetPosListResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/GetPosByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posServiceClient) PosDetail(ctx context.Context, in *PosDetailRequest, opts ...grpc.CallOption) (*PosDetailResponse, error) {
	out := new(PosDetailResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/PosDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posServiceClient) UpdatePosByUser(ctx context.Context, in *UpdatePosRequest, opts ...grpc.CallOption) (*UpdatePosResponse, error) {
	out := new(UpdatePosResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/UpdatePosByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posServiceClient) DeletePosByUser(ctx context.Context, in *DeletePosRequest, opts ...grpc.CallOption) (*DeletePosResponse, error) {
	out := new(DeletePosResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/DeletePosByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posServiceClient) UpdateTotalPosByUser(ctx context.Context, in *UpdateTotalPosRequest, opts ...grpc.CallOption) (*UpdateTotalPosResponse, error) {
	out := new(UpdateTotalPosResponse)
	err := c.cc.Invoke(ctx, "/pos.PosService/UpdateTotalPosByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PosServiceServer is the server API for PosService service.
type PosServiceServer interface {
	CreatePos(context.Context, *CreatePosRequest) (*CreatePosResponse, error)
	GetPosByUser(context.Context, *GetPosListRequest) (*GetPosListResponse, error)
	PosDetail(context.Context, *PosDetailRequest) (*PosDetailResponse, error)
	UpdatePosByUser(context.Context, *UpdatePosRequest) (*UpdatePosResponse, error)
	DeletePosByUser(context.Context, *DeletePosRequest) (*DeletePosResponse, error)
	UpdateTotalPosByUser(context.Context, *UpdateTotalPosRequest) (*UpdateTotalPosResponse, error)
}

// UnimplementedPosServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPosServiceServer struct {
}

func (*UnimplementedPosServiceServer) CreatePos(context.Context, *CreatePosRequest) (*CreatePosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePos not implemented")
}
func (*UnimplementedPosServiceServer) GetPosByUser(context.Context, *GetPosListRequest) (*GetPosListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosByUser not implemented")
}
func (*UnimplementedPosServiceServer) PosDetail(context.Context, *PosDetailRequest) (*PosDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PosDetail not implemented")
}
func (*UnimplementedPosServiceServer) UpdatePosByUser(context.Context, *UpdatePosRequest) (*UpdatePosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosByUser not implemented")
}
func (*UnimplementedPosServiceServer) DeletePosByUser(context.Context, *DeletePosRequest) (*DeletePosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePosByUser not implemented")
}
func (*UnimplementedPosServiceServer) UpdateTotalPosByUser(context.Context, *UpdateTotalPosRequest) (*UpdateTotalPosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTotalPosByUser not implemented")
}

func RegisterPosServiceServer(s *grpc.Server, srv PosServiceServer) {
	s.RegisterService(&_PosService_serviceDesc, srv)
}

func _PosService_CreatePos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).CreatePos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/CreatePos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).CreatePos(ctx, req.(*CreatePosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PosService_GetPosByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPosListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).GetPosByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/GetPosByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).GetPosByUser(ctx, req.(*GetPosListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PosService_PosDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).PosDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/PosDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).PosDetail(ctx, req.(*PosDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PosService_UpdatePosByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).UpdatePosByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/UpdatePosByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).UpdatePosByUser(ctx, req.(*UpdatePosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PosService_DeletePosByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).DeletePosByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/DeletePosByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).DeletePosByUser(ctx, req.(*DeletePosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PosService_UpdateTotalPosByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTotalPosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).UpdateTotalPosByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.PosService/UpdateTotalPosByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).UpdateTotalPosByUser(ctx, req.(*UpdateTotalPosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PosService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pos.PosService",
	HandlerType: (*PosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePos",
			Handler:    _PosService_CreatePos_Handler,
		},
		{
			MethodName: "GetPosByUser",
			Handler:    _PosService_GetPosByUser_Handler,
		},
		{
			MethodName: "PosDetail",
			Handler:    _PosService_PosDetail_Handler,
		},
		{
			MethodName: "UpdatePosByUser",
			Handler:    _PosService_UpdatePosByUser_Handler,
		},
		{
			MethodName: "DeletePosByUser",
			Handler:    _PosService_DeletePosByUser_Handler,
		},
		{
			MethodName: "UpdateTotalPosByUser",
			Handler:    _PosService_UpdateTotalPosByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions/pb/pos.proto",
}
